base_url = "https://altunenes.github.io/"
title = "altunenes"
description = "personal blog"
build_search_index = false
generate_feeds = true
compile_sass = true
minify_html = true
taxonomies = [{ name = "tags" }]
theme = "apollo"
[markdown]
highlight_code = true
highlight_theme = "ayu-dark"

[extra]
toc = true
use_cdn = false
favicon = "/icon/favicon.png"
theme = "toggle"              # light, dark, auto, toggle
comment = false
# mathjax = true
# mathjax_dollar_inline_enable = true

menu = [
    { name = "/posts", url = "/posts", weight = 1 },
    { name = "/projects&Demos", url = "/projects", weight = 2 },
    { name = "/about", url = "/about", weight = 3 },
    { name = "/tags", url = "/tags", weight = 4 },
    { name = "/CV", url = "/CV", weight = 5 },

]

socials = [
    { name = "twitter", url = "https://twitter.com/emportent", icon = "twitter" },
    { name = "github", url = "https://github.com/altunenes", icon = "github" },
    { name = "scholar", url = "https://scholar.google.com/citations?user=_OtEw5oAAAAJ&hl", icon = "googlescholar" },
    { name = "linkedin", url = "https://www.linkedin.com/in/enes-altun-0a3076167", icon = "linkedin" },
    { name = "instagram", url = "https://www.instagram.com/altunanes/", icon = "instagram" },
    { name = "orcid", url = "https://orcid.org/0000-0002-6478-6909", icon = "orcid" },
    { name = "kaggle", url = "https://www.kaggle.com/enesaltun", icon = "kaggle" },
    { name = "shadertoy", url = "https://www.shadertoy.com/user/altunenes", icon = "shadertoy" },
    { name = "stackoverflow", url = "https://stackoverflow.com/users/14492150/altune", icon = "stackoverflow" },
    { name = "bluesky", url = "https://bsky.app/profile/altunenes.bsky.social", icon = "bluesky" }
    
]

custom_css = []

[extra.analytics]
enabled = false

[extra.analytics.goatcounter]
user = "your_user"
host = "example.com" # default= goatcounter.com

[extra.analytics.umami]
website_id = "43929cd1-1e83...."
host_url = "https://stats.mywebsite.com" # default: https://analytics.eu.umami.is